language: go

sudo: false

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

install:
  - go get -d -t ./...
  - go get -u github.com/golang/lint/...

script:
  - golint ./...
  - go vet ./...
  - go test -v -race -cover ./...
